In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## Define the vocabulary size
voc_size=10000

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
##One hot representation 
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3572, 1390, 9317, 2465],
 [3572, 1390, 9317, 3098],
 [3572, 410, 9317, 491],
 [4717, 6890, 4929, 3564, 8756],
 [4717, 6890, 4929, 3564, 6721],
 [6318, 3572, 4796, 9317, 2345],
 [113, 9301, 9275, 3564]]

In [13]:
## word embedding llayer 
from tensorflow.keras.layers import Embedding
###from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np


In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3572 1390 9317 2465]
 [   0    0    0    0 3572 1390 9317 3098]
 [   0    0    0    0 3572  410 9317  491]
 [   0    0    0 4717 6890 4929 3564 8756]
 [   0    0    0 4717 6890 4929 3564 6721]
 [   0    0    0 6318 3572 4796 9317 2345]
 [   0    0    0    0  113 9301 9275 3564]]


In [16]:
## feature Representation
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 160ms/step


array([[[ 0.01981064, -0.03458717, -0.01025064,  0.03181464,
         -0.0271955 ,  0.0098789 ,  0.03642168, -0.00798135,
          0.02707282, -0.02474059],
        [ 0.01981064, -0.03458717, -0.01025064,  0.03181464,
         -0.0271955 ,  0.0098789 ,  0.03642168, -0.00798135,
          0.02707282, -0.02474059],
        [ 0.01981064, -0.03458717, -0.01025064,  0.03181464,
         -0.0271955 ,  0.0098789 ,  0.03642168, -0.00798135,
          0.02707282, -0.02474059],
        [ 0.01981064, -0.03458717, -0.01025064,  0.03181464,
         -0.0271955 ,  0.0098789 ,  0.03642168, -0.00798135,
          0.02707282, -0.02474059],
        [-0.00438782, -0.03679575,  0.00259275, -0.02264574,
         -0.00340266,  0.01060491,  0.04860253,  0.03492106,
          0.00926044,  0.0255901 ],
        [ 0.02189113,  0.03306648, -0.01743982, -0.01350784,
         -0.03116879,  0.03645276,  0.01686472, -0.0054662 ,
          0.0308898 ,  0.01719438],
        [-0.01274694,  0.00451677, -0.00408852,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 3572, 1390, 9317, 2465])

In [21]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 38ms/step


array([[ 0.01981064, -0.03458717, -0.01025064,  0.03181464, -0.0271955 ,
         0.0098789 ,  0.03642168, -0.00798135,  0.02707282, -0.02474059],
       [ 0.01981064, -0.03458717, -0.01025064,  0.03181464, -0.0271955 ,
         0.0098789 ,  0.03642168, -0.00798135,  0.02707282, -0.02474059],
       [ 0.01981064, -0.03458717, -0.01025064,  0.03181464, -0.0271955 ,
         0.0098789 ,  0.03642168, -0.00798135,  0.02707282, -0.02474059],
       [ 0.01981064, -0.03458717, -0.01025064,  0.03181464, -0.0271955 ,
         0.0098789 ,  0.03642168, -0.00798135,  0.02707282, -0.02474059],
       [-0.00438782, -0.03679575,  0.00259275, -0.02264574, -0.00340266,
         0.01060491,  0.04860253,  0.03492106,  0.00926044,  0.0255901 ],
       [ 0.02189113,  0.03306648, -0.01743982, -0.01350784, -0.03116879,
         0.03645276,  0.01686472, -0.0054662 ,  0.0308898 ,  0.01719438],
       [-0.01274694,  0.00451677, -0.00408852,  0.04568154,  0.02016078,
        -0.03184341, -0.01223224,  0.04913712